apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: users
spec:
  selector:
    app: users-microservice
  ports:
    - port: 80
      targetPort: 5050
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: users-service-clusterip
  namespace: users
spec:
  selector:
    app: users-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5050
  type: ClusterIP